import Link from 'next/link';

const dimensions=[['Music & sound','Strong'],['Artist identity','Strong'],['Audience & momentum','Developing'],['Live profile','Needs attention'],['Professional setup','Strong'],['Release direction','Developing']];
const services=[
  {tag:'PROFILE',title:'Build my professional EPK',desc:'We turn your bio, music, press shots, links and live material into one professional artist package.',price:'From €79',fit:'Recommended for you'},
  {tag:'CONTENT',title:'Create my release content pack',desc:'A ready-to-use direction for your next release with content ideas, copy, formats and a practical posting plan.',price:'From €99',fit:'Matches your next move'},
  {tag:'PRESENCE',title:'Strengthen my artist profiles',desc:'Sharpen your Spotify, SoundCloud, Instagram, TikTok and YouTube presence so your artist story feels consistent everywhere.',price:'From €59',fit:'Profile opportunity'},
  {tag:'RELEASE',title:'Build my release strategy',desc:'Positioning, timeline, assets, pitching preparation and the priorities around your next single.',price:'From €129',fit:'High impact'}
];

export default function Artist(){return <main><div className="wrap"><nav className="nav"><Link className="brand" href="/">AU·RA</Link><span className="pill">Artist profile · Demo</span></nav>
<section className="section"><p className="eyebrow">YOUR ARTIST PROFILE</p><h2>Jordan Vale</h2><p className="muted">Electronic / Afro House · Amsterdam</p></section>
<section className="split"><div className="callout"><p>ARTIST REVIEW</p><div className="score" style={{fontSize:42}}>Strong potential</div><h2 style={{fontSize:36}}>Your profile is moving in the right direction.</h2><p className="muted">Your sound and identity stand out. The biggest opportunity now is building stronger live proof and a more consistent release story.</p><div className="actions"><a className="btn" href="#next">View feedback</a></div></div><div className="card"><p className="muted">PROFILE REVIEW</p>{dimensions.map(([name,status])=><div className="item" key={name}><span>{name}</span><b>{status}</b></div>)}</div></section>
<section className="section" id="next"><p className="eyebrow">RECOMMENDED NEXT STEPS</p><h2>Where to focus next.</h2><div className="grid"><div className="card next-card"><span className="tag">PRIORITY</span><h3>Complete your EPK</h3><p className="muted">Add one strong recent live clip, updated press shots and a concise professional bio.</p><div className="next-actions"><a href="#services">See how →</a><a className="service-link" href="#services">Let AU·RA handle it</a></div></div><div className="card next-card"><span className="tag">RELEASE</span><h3>Prepare your next single</h3><p className="muted">Your current direction could benefit from a focused label-first release strategy and a clear pitching window.</p><div className="next-actions"><a href="#services">View direction →</a><a className="service-link" href="#services">Build it with AU·RA</a></div></div><div className="card next-card"><span className="tag">LIVE</span><h3>Build more live proof</h3><p className="muted">Recent high-quality performance content will strengthen both your booking profile and your overall artist story.</p><div className="next-actions"><a href="#services">View advice →</a><a className="service-link" href="#services">Get content support</a></div></div></div></section>

<section className="section services-section" id="services"><div className="section-head"><div><p className="eyebrow">AU·RA SERVICES</p><h2>Know what to do.<br/>Or let us help you do it.</h2></div><p className="lead small-lead">Your review stays useful whether you spend anything or not. If you want help executing a recommendation, you can hand selected parts of the work to AU·RA.</p></div><div className="service-grid">{services.map((s,i)=><div className={`service-card ${i===0?'featured-service':''}`} key={s.title}><div className="service-top"><span className="tag">{s.tag}</span><span className="service-fit">{s.fit}</span></div><h3>{s.title}</h3><p>{s.desc}</p><div className="service-bottom"><div><small>GUIDE PRICE</small><b>{s.price}</b></div><button>Explore service ↗</button></div></div>)}</div><div className="service-note"><span>Good to know</span><p>Using AU·RA Services never increases your chance of representation. We select artists on music, ambition, momentum and fit — not on what they buy.</p></div></section>

<section className="section" id="representation"><div className="card representation-card"><p className="eyebrow">REPRESENTATION</p><h2 style={{fontSize:42}}>Could there be a fit?</h2><p className="muted">Selected profiles can be invited for a personal agency review. Representation is always based on music, ambition, momentum and a genuine mutual fit.</p><div className="actions"><a className="btn" href="#">Submit for consideration</a></div></div></section></div></main>}
