import Link from 'next/link';

const priority=[
  ['Mila West','Label follow-up','Interest open for 5 days','Today'],
  ['Jordan Vale','Release review','Midnight Bloom has 3 relevant label routes','Today'],
  ['KAIRO','Artist assets','Live profile is blocking booking outreach','Tomorrow']
];
const roster=[['NOVA LANE','Dance / Pop','Representation','Rising'],['Mila West','Pop / Electronic','Review','Strong'],['Jordan Vale','Afro House','Development','Building'],['KAIRO','Melodic House','Development','Building']];
const pipeline=[['Afterglow','Mila West','Negotiation','Warm contact'],['Midnight Bloom','Jordan Vale','Pitching','3 routes'],['Signal','KAIRO','Preparing','Assets needed']];

export default function Dashboard(){return <div className="dash agency-shell"><aside className="side agency-side"><Link className="brand" href="/">AU·RA</Link><p className="side-label">MANAGEMENT</p><Link className="active" href="/dashboard">Home <span>⌂</span></Link><a href="#roster">Artists <span>04</span></a><a href="#releases">Releases <span>03</span></a><a href="#opportunities">Opportunities <span>07</span></a><a href="#network">Network <span>42</span></a><a href="#tasks">Tasks <span>03</span></a><div className="side-bottom"><span className="avatar">PO</span><div><b>Parel On</b><small>Agency workspace</small></div></div></aside><main className="main agency-main"><header className="agency-top"><div><p className="eyebrow">SATURDAY · 22 AUGUST</p><h1>Morning. Here’s what matters.</h1></div><div className="top-actions"><button className="icon-btn">⌕</button><button className="dark-btn">+ Add artist</button></div></header>

      <section className="agency-hero-grid"><div className="focus-panel"><div className="panel-top"><span className="eyebrow">TODAY'S FOCUS</span><span className="status-live"><i/>3 actions</span></div><h2>Keep the momentum moving.</h2><div className="priority-list">{priority.map(([artist,type,desc,due],i)=><div className="priority-row" key={artist}><span className="priority-index">0{i+1}</span><div className="priority-copy"><b>{artist}</b><span>{type} · {desc}</span></div><span className="due">{due}</span><button className="arrow-btn">↗</button></div>)}</div></div><div className="pulse-panel"><p className="eyebrow">AGENCY PULSE</p><div className="pulse-number">7</div><h3>live opportunities</h3><p className="muted">2 warm label routes<br/>3 booking fits<br/>2 artists worth reviewing</p><div className="mini-bars"><span style={{height:'35%'}}/><span style={{height:'55%'}}/><span style={{height:'46%'}}/><span style={{height:'78%'}}/><span style={{height:'68%'}}/><span style={{height:'92%'}}/><span style={{height:'82%'}}/></div></div></section>

      <section className="quick-stats"><div><span>ACTIVE ARTISTS</span><strong>04</strong><small>1 represented · 3 developing</small></div><div><span>RELEASES MOVING</span><strong>03</strong><small>1 deal in negotiation</small></div><div><span>WARM RELATIONSHIPS</span><strong>09</strong><small>Across labels & booking</small></div><div><span>FOLLOW-UP HEALTH</span><strong>84%</strong><small>4 conversations this week</small></div></section>

      <section className="agency-section" id="roster"><div className="section-head compact"><div><p className="eyebrow">ROSTER</p><h2>Artists</h2></div><a className="text-link" href="#">View all →</a></div><div className="artist-cards">{roster.map(([name,genre,status,momentum],i)=><div className="artist-card" key={name}><div className={`artist-art art-${i+1}`}><span>{name.slice(0,1)}</span></div><div className="artist-meta"><div><h3>{name}</h3><p>{genre}</p></div><span className="tag">{status}</span></div><div className="artist-foot"><span>Momentum</span><b>{momentum} ↗</b></div></div>)}</div></section>

      <section className="agency-two-col"><div className="agency-section" id="releases"><div className="section-head compact"><div><p className="eyebrow">RELEASE PIPELINE</p><h2>Moving now</h2></div></div><div className="clean-list">{pipeline.map(([release,artist,stage,signal])=><div className="clean-row" key={release}><div><b>{release}</b><span>{artist}</span></div><span className="stage">{stage}</span><span className="muted">{signal}</span><button className="arrow-btn">↗</button></div>)}</div></div><div className="agency-section" id="opportunities"><div className="section-head compact"><div><p className="eyebrow">OPPORTUNITIES</p><h2>Worth a look</h2></div></div><div className="opp-stack"><div className="opp-card"><span className="opp-type">LABEL</span><b>Midnight Bloom</b><p>Jordan Vale · warm route available</p><strong>Strong fit</strong></div><div className="opp-card"><span className="opp-type">BOOKING</span><b>Amsterdam · September</b><p>NOVA LANE · profile aligned</p><strong>New</strong></div></div></div></section>

      <section className="agency-section network-strip" id="network"><div><p className="eyebrow">PRIVATE NETWORK</p><h2>42 relationships. 9 warm right now.</h2><p className="muted">Your label, A&R, booking and promoter relationships stay private — AU·RA keeps the context, history and next follow-up in one place.</p></div><div className="network-nodes"><span>Labels<b>18</b></span><span>Booking<b>11</b></span><span>Promoters<b>13</b></span></div></section>

      <section className="agency-section" id="tasks"><div className="section-head compact"><div><p className="eyebrow">THIS WEEK</p><h2>Nothing falls through.</h2></div></div><div className="task-line"><span>Follow up Mila West label interest</span><b>Today</b><button>Done</button></div><div className="task-line"><span>Review Midnight Bloom shortlist</span><b>Today</b><button>Done</button></div><div className="task-line"><span>Request KAIRO live content</span><b>Tomorrow</b><button>Done</button></div></section>
    </main></div>}
